import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CreditCard } from "lucide-react";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminPayments } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";
export const Route = createFileRoute("/admin/paiements")({ component: AdminPaymentsPage });
function AdminPaymentsPage() { const demo = isLocalDemo(); const getPayments = useServerFn(getAdminPayments); const query = useQuery({ queryKey: ["admin", "payments"], queryFn: () => getPayments({ data: { page: 1, pageSize: 50, search: "" } }), enabled: !demo }); const payments = demo ? [{ id: "demo", user_id: "demo", provider: "fapshi", pack_id: "premium-annual", credits: 100, amount_xaf: 25000, status: "SUCCESSFUL", created_at: new Date().toISOString() }] : query.data?.payments ?? []; return <AdminSection eyebrow="Finance" title="Paiements & abonnements" description="Suivez les transactions et identifiez rapidement les paiements nécessitant une vérification.">{!demo && query.isLoading ? <AdminLoading /> : <AdminCard className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-border/60 bg-surface"><tr>{["Transaction", "Provider", "Pack", "Montant", "Crédits", "Statut", "Date"].map((label) => <th key={label} className="p-3 font-black">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{payments.map((payment) => <tr key={payment.id}><td className="p-3"><p className="font-black">{payment.id}</p><p className="text-[10px] text-muted-foreground">{payment.user_id}</p></td><td className="p-3">{payment.provider}</td><td className="p-3 font-bold">{payment.pack_id}</td><td className="p-3 font-black">{Number(payment.amount_xaf).toLocaleString("fr-FR")} FCFA</td><td className="p-3 text-brand">{payment.credits}</td><td className="p-3 font-black">{payment.status}</td><td className="p-3 text-muted-foreground">{new Date(payment.created_at).toLocaleDateString("fr-FR")}</td></tr>)}</tbody></table></AdminCard>}{!payments.length && <AdminCard><CreditCard className="size-5 text-muted-foreground" /><p className="mt-2 text-sm font-bold">Aucun paiement récent</p></AdminCard>}</AdminSection>; }
