import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Download, FileJson, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { AdminCard, AdminSection } from "@/components/AdminShell";
import { exportAdminData } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";
export const Route = createFileRoute("/admin/exports")({ component: AdminExportsPage });
function AdminExportsPage() { const demo = isLocalDemo(); const exportData = useServerFn(exportAdminData); const [dataset, setDataset] = useState<"users" | "payments" | "analyses" | "audit">("users"); const [format, setFormat] = useState<"csv" | "json">("csv"); const [message, setMessage] = useState(""); async function handleExport() { if (demo) { setMessage("Aperçu local : aucun export serveur n'est généré."); return; } try { const result = await exportData({ data: { dataset, format, limit: 500 } }); const blob = new Blob([result.content], { type: result.mime }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.filename; anchor.click(); URL.revokeObjectURL(url); setMessage("Export généré et journalisé."); } catch { setMessage("Export refusé ou momentanément indisponible."); } } return <AdminSection eyebrow="Données contrôlées" title="Exports" description="Téléchargez uniquement les données nécessaires. Chaque export est limité, masqué si nécessaire et journalisé."><AdminCard className="max-w-2xl"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Jeu de données<select value={dataset} onChange={(event) => setDataset(event.target.value as typeof dataset)} className="mt-2 h-10 w-full rounded-xl border border-border bg-background px-3 text-xs"><option value="users">Utilisateurs</option><option value="payments">Paiements</option><option value="analyses">Analyses</option><option value="audit">Audit (owner)</option></select></label><label className="text-xs font-bold">Format<select value={format} onChange={(event) => setFormat(event.target.value as typeof format)} className="mt-2 h-10 w-full rounded-xl border border-border bg-background px-3 text-xs"><option value="csv">CSV</option><option value="json">JSON</option></select></label></div><button type="button" onClick={() => void handleExport()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-brand px-4 py-3 text-xs font-black text-brand-foreground"><Download className="size-4" /> Générer l’export</button>{message && <p className="mt-3 text-xs text-muted-foreground">{message}</p>}</AdminCard><div className="flex max-w-2xl items-start gap-2 text-xs text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-brand" />Les secrets, tokens et mots de passe ne font jamais partie des exports.<FileJson className="ml-auto size-4" /></div></AdminSection>; }
