import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Activity, CheckCircle2, Database, KeyRound, RefreshCw, Server } from "lucide-react";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminApiHealth } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";
export const Route = createFileRoute("/admin/api")({ component: AdminApiPage });
function AdminApiPage() { const demo = isLocalDemo(); const getHealth = useServerFn(getAdminApiHealth); const query = useQuery({ queryKey: ["admin", "api"], queryFn: () => getHealth(), enabled: !demo, refetchInterval: 30_000 }); const data = demo ? { apiFootball: { configured: true, quota: { dayRemaining: 6412, dayLimit: 7500, minuteRemaining: 278, minuteLimit: 300 }, cache: { stale: false, storedAt: Date.now() - 12000 } }, aiConfigured: true, fapshiConfigured: true, cloudflareConfigured: true, checkedAt: new Date().toISOString() } : query.data; if (!demo && query.isLoading) return <AdminLoading />; const services = [{ label: "API-Football", ok: data?.apiFootball.configured, Icon: KeyRound }, { label: "Cache partagé", ok: Boolean(data?.apiFootball.cache), Icon: Database }, { label: "IA", ok: data?.aiConfigured, Icon: Activity }, { label: "Cloudflare", ok: data?.cloudflareConfigured, Icon: Server }]; return <AdminSection eyebrow="Observabilité" title="Matchs & API" description="Surveillez les dépendances sans afficher leurs secrets ni leurs valeurs sensibles."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{services.map(({ label, ok, Icon }) => <AdminCard key={label}><Icon className="size-5 text-brand" /><p className="mt-3 text-sm font-black">{label}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground">{ok ? <CheckCircle2 className="size-3 text-brand" /> : <span className="size-2 rounded-full bg-alert" />}{ok ? "Opérationnel" : "À vérifier"}</p></AdminCard>)}</div><AdminCard><div className="flex items-center justify-between"><div><p className="text-sm font-black">Quota API-Football</p><p className="mt-1 text-xs text-muted-foreground">La cadence réelle reste pilotée par les headers fournisseur et le cache partagé.</p></div><RefreshCw className="size-5 text-brand" /></div><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Jour restant", data?.apiFootball.quota.dayRemaining ?? "—"], ["Limite jour", data?.apiFootball.quota.dayLimit ?? "—"], ["Minute restante", data?.apiFootball.quota.minuteRemaining ?? "—"], ["Limite minute", data?.apiFootball.quota.minuteLimit ?? "—"]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-surface p-3"><p className="text-[10px] font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div></AdminCard></AdminSection>; }
