import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Search, ShieldAlert, UserCheck, UserX } from "lucide-react";
import { useState } from "react";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminUsers, restoreAdminUser, suspendAdminUser } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";

export const Route = createFileRoute("/admin/utilisateurs")({ component: AdminUsersPage });
const DEMO_USERS = { users: [{ id: "demo-1", email: "dodo@example.com", displayName: "Dodo", plan: "premium", credits: 84, accountStatus: "active", roles: ["owner"], createdAt: "2026-07-01T10:00:00Z", premiumUntil: "2027-07-01T10:00:00Z" }, { id: "demo-2", email: "support@example.com", displayName: "Support", plan: "free", credits: 5, accountStatus: "suspended", roles: ["user"], createdAt: "2026-07-05T10:00:00Z", premiumUntil: null }], hasMore: false };
function AdminUsersPage() {
  const demo = isLocalDemo(); const [search, setSearch] = useState(""); const [reason, setReason] = useState(""); const [selected, setSelected] = useState<string | null>(null); const queryClient = useQueryClient(); const getUsers = useServerFn(getAdminUsers); const suspend = useServerFn(suspendAdminUser); const restore = useServerFn(restoreAdminUser);
  const query = useQuery({ queryKey: ["admin", "users", search], queryFn: () => getUsers({ data: { page: 1, pageSize: 50, search } }), enabled: !demo }); const data = demo ? DEMO_USERS : query.data;
  async function mutate(userId: string, action: "suspend" | "restore") { if (reason.trim().length < 8) return; if (demo) return; try { if (action === "suspend") await suspend({ data: { userId, reason } }); else await restore({ data: { userId, reason } }); setReason(""); setSelected(null); await queryClient.invalidateQueries({ queryKey: ["admin", "users"] }); } catch { /* surface is kept stable; the server remains authoritative */ } }
  return <AdminSection eyebrow="Gestion des comptes" title="Utilisateurs" description="Recherchez, surveillez et modérez les comptes sans exposer de données sensibles."><AdminCard><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Email, nom ou identifiant…" className="h-10 w-full rounded-xl border border-border/70 bg-background pl-9 pr-3 text-xs font-bold outline-none focus:border-brand" /></div></AdminCard>{!demo && query.isLoading ? <AdminLoading /> : <AdminCard className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-border/60 bg-surface"><tr>{["Utilisateur", "Plan", "Crédits", "Rôle", "État", "Action"].map((label) => <th key={label} className="p-3 font-black">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{(data?.users ?? []).map((user) => <tr key={user.id}><td className="p-3"><p className="font-black">{user.displayName ?? "Sans nom"}</p><p className="mt-1 text-[10px] text-muted-foreground">{user.email ?? user.id}</p></td><td className="p-3 font-bold">{user.plan}</td><td className="p-3 font-black text-brand">{user.credits}</td><td className="p-3">{user.roles.map((role) => <span key={role} className="mr-1 rounded-full bg-surface px-2 py-1 text-[10px] font-black">{role}</span>)}</td><td className="p-3"><span className={user.accountStatus === "active" ? "text-brand" : "text-alert"}>{user.accountStatus === "active" ? "Actif" : "Suspendu"}</span></td><td className="p-3">{selected === user.id ? <div className="flex min-w-[260px] items-center gap-2"><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Motif obligatoire" className="h-8 flex-1 rounded-lg border border-border bg-background px-2 text-[10px]" /><button type="button" onClick={() => void mutate(user.id, user.accountStatus === "active" ? "suspend" : "restore")} className="rounded-lg bg-foreground px-2 py-2 text-[10px] font-black text-background">Confirmer</button></div> : <button type="button" onClick={() => setSelected(user.id)} className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-2 text-[10px] font-black">{user.accountStatus === "active" ? <><UserX className="size-3" /> Suspendre</> : <><UserCheck className="size-3" /> Réactiver</>}</button>}</td></tr>)}</tbody></table></AdminCard>}{selected && <p className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldAlert className="size-4 text-warn" /> Toute suspension est réversible et enregistrée dans l’audit.</p>}</AdminSection>;
}
