import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CheckCircle2, Clock3, Crown, FileCheck2, XCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminVipApplications, requestVipGrantApproval, reviewVipApplication } from "@/lib/vip.functions";

export const Route = createFileRoute("/admin/vip")({ component: AdminVipPage });

function AdminVipPage() {
  const getApplications = useServerFn(getAdminVipApplications);
  const review = useServerFn(reviewVipApplication);
  const requestApproval = useServerFn(requestVipGrantApproval);
  const query = useQuery({ queryKey: ["admin", "vip"], queryFn: () => getApplications({ data: { page: 1, pageSize: 100, status: "all" } }), refetchInterval: 30_000 });
  const [busy, setBusy] = useState<string | null>(null);
  async function update(applicationId: string, status: "under_review" | "needs_info" | "rejected") { setBusy(applicationId); try { await review({ data: { applicationId, status, reason: status === "rejected" ? "Les éléments transmis ne permettent pas de confirmer l’éligibilité." : status === "needs_info" ? "Merci de compléter les informations de dépôt." : "Dossier pris en charge pour vérification." } }); await query.refetch(); toast.success("Demande mise à jour."); } catch (error) { toast.error(error instanceof Error ? error.message : "Action impossible."); } finally { setBusy(null); } }
  async function submitApproval(applicationId: string) { setBusy(applicationId); try { await requestApproval({ data: { applicationId, reason: "Dossier vérifié, demande de validation propriétaire." } }); await query.refetch(); toast.success("Demande envoyée pour validation propriétaire."); } catch (error) { toast.error(error instanceof Error ? error.message : "Validation impossible."); } finally { setBusy(null); } }
  if (query.isLoading) return <AdminLoading />;
  const applications = query.data?.applications ?? [];
  return <AdminSection eyebrow="Programme partenaire" title="Demandes VIP" description="Vérifiez les dossiers, demandez les informations manquantes et soumettez les activations à la validation propriétaire."><AdminCard className="overflow-x-auto p-0"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-border/60 bg-surface"><tr>{["Offre", "Utilisateur", "Partenaire", "Dépôt", "Compte", "Statut", "Actions"].map((label) => <th key={label} className="p-3 font-black">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{applications.map((item: any) => <tr key={item.id}><td className="p-3"><span className="inline-flex items-center gap-1 font-black"><Crown className="size-3 text-brand" />{item.tier === "pro" ? "Pro · 6 mois" : "Starter · 3 mois"}</span><p className="mt-1 text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleDateString("fr-FR")}</p></td><td className="p-3"><p className="font-bold">{item.full_name}</p><p className="text-[10px] text-muted-foreground">{item.contact_email}</p></td><td className="p-3"><p className="font-bold">{item.partner_slug}</p><p className="text-[10px] text-brand">{item.promo_code}</p></td><td className="p-3 font-black">{Number(item.deposit_amount_xaf).toLocaleString("fr-FR")} FCFA<p className="text-[10px] font-normal text-muted-foreground">{item.deposit_reference}</p></td><td className="p-3 font-mono text-[10px]">{item.bookmaker_account_id}</td><td className="p-3"><Status status={item.status} /></td><td className="p-3"><div className="flex flex-wrap gap-1.5">{["submitted", "needs_info"].includes(item.status) && <button type="button" disabled={busy === item.id} onClick={() => void update(item.id, "under_review")} className="rounded-lg bg-surface px-2 py-1.5 text-[10px] font-bold">Vérifier</button>}{["submitted", "under_review", "needs_info"].includes(item.status) && <button type="button" disabled={busy === item.id} onClick={() => void submitApproval(item.id)} className="rounded-lg bg-brand px-2 py-1.5 text-[10px] font-black text-brand-foreground"><FileCheck2 className="mr-1 inline size-3" />Soumettre</button>}{!["approved", "rejected", "expired"].includes(item.status) && <><button type="button" disabled={busy === item.id} onClick={() => void update(item.id, "needs_info")} className="rounded-lg bg-warn/15 px-2 py-1.5 text-[10px] font-bold text-warn">Infos</button><button type="button" disabled={busy === item.id} onClick={() => void update(item.id, "rejected")} className="rounded-lg bg-alert/10 px-2 py-1.5 text-[10px] font-bold text-alert">Refuser</button></>}</div></td></tr>)}</tbody></table>{!applications.length && <p className="p-10 text-center text-xs text-muted-foreground">Aucune demande VIP.</p>}</AdminCard><p className="text-[11px] text-muted-foreground">Une activation Premium n’est effective qu’après validation d’un propriétaire distinct dans Audit & sécurité.</p></AdminSection>;
}
function Status({ status }: { status: string }) { const map: Record<string, [string, string, any]> = { submitted: ["Reçue", "text-sky-500", Clock3], under_review: ["En vérification", "text-warn", Clock3], needs_info: ["Infos demandées", "text-warn", FileCheck2], approved: ["Approuvée", "text-brand", CheckCircle2], rejected: ["Refusée", "text-alert", XCircle], expired: ["Expirée", "text-muted-foreground", Clock3] }; const [label, color, Icon] = map[status] ?? map.submitted; return <span className={`inline-flex items-center gap-1 font-black ${color}`}><Icon className="size-3" />{label}</span>; }
