import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { MessageCircle, Users } from "lucide-react";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminCommunity } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";
export const Route = createFileRoute("/admin/communaute")({ component: AdminCommunityPage });
function AdminCommunityPage() { const demo = isLocalDemo(); const getCommunity = useServerFn(getAdminCommunity); const query = useQuery({ queryKey: ["admin", "community"], queryFn: () => getCommunity(), enabled: !demo }); const data = demo ? { messages: [{ id: "demo", user_name: "Fan LiveFoot", message: "Bonne analyse pour ce soir !", created_at: new Date().toISOString() }], predictions: [{ id: "demo-p", user_name: "Fan LiveFoot", home_team: "Arsenal", away_team: "Chelsea", prediction: "home", created_at: new Date().toISOString() }] } : query.data; if (!demo && query.isLoading) return <AdminLoading />; return <AdminSection eyebrow="Modération" title="Communauté" description="Surveillez les messages et les prédictions partagées par la communauté."><div className="grid gap-4 xl:grid-cols-2"><AdminCard><div className="flex items-center gap-2"><MessageCircle className="size-4 text-brand" /><p className="text-sm font-black">Messages récents</p></div><div className="mt-4 space-y-2">{(data?.messages ?? []).map((message: any) => <div key={message.id} className="rounded-xl bg-surface p-3"><p className="text-xs font-black">{message.user_name}</p><p className="mt-1 text-xs text-muted-foreground">{message.message}</p></div>)}</div></AdminCard><AdminCard><div className="flex items-center gap-2"><Users className="size-4 text-brand" /><p className="text-sm font-black">Votes et prédictions</p></div><div className="mt-4 space-y-2">{(data?.predictions ?? []).map((prediction: any) => <div key={prediction.id} className="rounded-xl bg-surface p-3"><p className="text-xs font-black">{prediction.home_team} vs {prediction.away_team}</p><p className="mt-1 text-xs text-muted-foreground">{prediction.user_name} · choix : {prediction.prediction}</p></div>)}</div></AdminCard></div></AdminSection>; }
