import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BarChart3 } from "lucide-react";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminAnalyses } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";
export const Route = createFileRoute("/admin/analyses")({ component: AdminAnalysesPage });
function AdminAnalysesPage() { const demo = isLocalDemo(); const getAnalyses = useServerFn(getAdminAnalyses); const query = useQuery({ queryKey: ["admin", "analyses"], queryFn: () => getAnalyses({ data: { page: 1, pageSize: 50, search: "" } }), enabled: !demo }); const rows = demo ? [{ id: "demo", user_id: "demo", home_team: "Arsenal", away_team: "Chelsea", match_id: "1", prediction_market: "1X2", prediction_pick: "Arsenal", prediction_confidence: 78, settlement_status: "won", final_score: "2-1", created_at: new Date().toISOString(), settled_at: new Date().toISOString() }] : query.data?.analyses ?? []; return <AdminSection eyebrow="Qualité prédictive" title="Analyses & prédictions" description="Lecture opérationnelle des analyses enregistrées et de leur règlement réel.">{!demo && query.isLoading ? <AdminLoading /> : <AdminCard className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-left text-xs"><thead className="border-b border-border/60 bg-surface"><tr>{["Match", "Marché", "Confiance", "Statut", "Score", "Créée"].map((label) => <th key={label} className="p-3 font-black">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{rows.map((row) => <tr key={row.id}><td className="p-3 font-black">{row.home_team} <span className="text-muted-foreground">vs</span> {row.away_team}</td><td className="p-3">{row.prediction_market ?? "—"}<p className="text-[10px] text-muted-foreground">{row.prediction_pick ?? "—"}</p></td><td className="p-3 text-brand">{row.prediction_confidence ?? "—"}%</td><td className="p-3 font-black">{row.settlement_status}</td><td className="p-3">{row.final_score ?? "—"}</td><td className="p-3 text-muted-foreground">{new Date(row.created_at).toLocaleDateString("fr-FR")}</td></tr>)}</tbody></table></AdminCard>}{!rows.length && <AdminCard><BarChart3 className="size-5 text-muted-foreground" /><p className="mt-2 text-sm font-bold">Aucune analyse enregistrée</p></AdminCard>}</AdminSection>; }
