import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { History, ShieldCheck } from "lucide-react";
import { AdminCard, AdminLoading, AdminSection } from "@/components/AdminShell";
import { getAdminActionRequests, getAdminAuditLog } from "@/lib/admin.functions";
import { isLocalDemo } from "@/lib/local-demo";
export const Route = createFileRoute("/admin/audit")({ component: AdminAuditPage });
function AdminAuditPage() { const demo = isLocalDemo(); const getAudit = useServerFn(getAdminAuditLog); const getRequests = useServerFn(getAdminActionRequests); const audit = useQuery({ queryKey: ["admin", "audit"], queryFn: () => getAudit({ data: { page: 1, pageSize: 100, search: "" } }), enabled: !demo }); const requests = useQuery({ queryKey: ["admin", "requests"], queryFn: () => getRequests(), enabled: !demo }); const entries = demo ? [{ id: "demo", actor_id: "owner", action: "user.suspend", target_type: "user", target_id: "demo", reason: "Test de modération", created_at: new Date().toISOString() }] : audit.data?.entries ?? []; return <AdminSection eyebrow="Traçabilité" title="Audit & sécurité" description="Historique immuable des actions administratives et demandes critiques."><AdminCard><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-brand" /><p className="text-sm font-black">Demandes critiques</p><span className="ml-auto rounded-full bg-warn/15 px-2 py-1 text-[10px] font-black text-warn">{demo ? 1 : requests.data?.filter((item: any) => item.status === "pending").length ?? 0} en attente</span></div><p className="mt-2 text-xs text-muted-foreground">Les actions irréversibles nécessitent un admin demandeur et un owner validateur distincts.</p></AdminCard>{!demo && audit.isLoading ? <AdminLoading /> : <AdminCard className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-border/60 bg-surface"><tr>{["Action", "Cible", "Motif", "Acteur", "Date"].map((label) => <th key={label} className="p-3 font-black">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{entries.map((entry: any) => <tr key={entry.id}><td className="p-3"><span className="inline-flex items-center gap-1 font-black"><History className="size-3 text-brand" />{entry.action}</span></td><td className="p-3">{entry.target_type} · {entry.target_id ?? "—"}</td><td className="p-3 text-muted-foreground">{entry.reason ?? "—"}</td><td className="p-3 text-muted-foreground">{entry.actor_id}</td><td className="p-3 text-muted-foreground">{new Date(entry.created_at).toLocaleString("fr-FR")}</td></tr>)}</tbody></table></AdminCard>}</AdminSection>; }
