/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CodesPromoRouteImport } from './routes/codes-promo'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedFavorisRouteImport } from './routes/_authenticated/favoris'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CodesPromoIndexRouteImport } from './routes/codes-promo.index'
import { Route as CodesPromoSlugRouteImport } from './routes/codes-promo.$slug'
import { Route as CodesPromoCamerounRouteImport } from './routes/codes-promo.cameroun'
import { Route as CodesPromoCoteIvoireRouteImport } from './routes/codes-promo.cote-ivoire'
import { Route as CodesPromoSenegalRouteImport } from './routes/codes-promo.senegal'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as PremiumHistoriqueRouteImport } from './routes/premium.historique'
import { Route as PremiumTableauDeBordRouteImport } from './routes/premium.tableau-de-bord'
import { Route as ApiPublicFapshiWebhookRouteImport } from './routes/api/public/fapshi-webhook'
import { Route as ApiPublicFixtureDiagnosticRouteImport } from './routes/api/public/fixture-diagnostic'
import { Route as CodesPromoSlugCountryRouteImport } from './routes/codes-promo.$slug.$country'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesPromoRoute = CodesPromoRouteImport.update({
  id: '/codes-promo',
  path: '/codes-promo',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavorisRoute = AuthenticatedFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const CodesPromoIndexRoute = CodesPromoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodesPromoRoute,
} as any)
const CodesPromoSlugRoute = CodesPromoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CodesPromoRoute,
} as any)
const CodesPromoCamerounRoute = CodesPromoCamerounRouteImport.update({
  id: '/cameroun',
  path: '/cameroun',
  getParentRoute: () => CodesPromoRoute,
} as any)
const CodesPromoCoteIvoireRoute = CodesPromoCoteIvoireRouteImport.update({
  id: '/cote-ivoire',
  path: '/cote-ivoire',
  getParentRoute: () => CodesPromoRoute,
} as any)
const CodesPromoSenegalRoute = CodesPromoSenegalRouteImport.update({
  id: '/senegal',
  path: '/senegal',
  getParentRoute: () => CodesPromoRoute,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumHistoriqueRoute = PremiumHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => PremiumRoute,
} as any)
const PremiumTableauDeBordRoute = PremiumTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => PremiumRoute,
} as any)
const ApiPublicFapshiWebhookRoute = ApiPublicFapshiWebhookRouteImport.update({
  id: '/api/public/fapshi-webhook',
  path: '/api/public/fapshi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFixtureDiagnosticRoute =
  ApiPublicFixtureDiagnosticRouteImport.update({
    id: '/api/public/fixture-diagnostic',
    path: '/api/public/fixture-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const CodesPromoSlugCountryRoute = CodesPromoSlugCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => CodesPromoSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRouteWithChildren
  '/codes-promo': typeof CodesPromoRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favoris': typeof AuthenticatedFavorisRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/codes-promo/$slug': typeof CodesPromoSlugRouteWithChildren
  '/codes-promo/cameroun': typeof CodesPromoCamerounRoute
  '/codes-promo/cote-ivoire': typeof CodesPromoCoteIvoireRoute
  '/codes-promo/senegal': typeof CodesPromoSenegalRoute
  '/live/$id': typeof LiveIdRoute
  '/match/$id': typeof MatchIdRoute
  '/premium/historique': typeof PremiumHistoriqueRoute
  '/premium/tableau-de-bord': typeof PremiumTableauDeBordRoute
  '/codes-promo/': typeof CodesPromoIndexRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
  '/api/public/fixture-diagnostic': typeof ApiPublicFixtureDiagnosticRoute
  '/codes-promo/$slug/$country': typeof CodesPromoSlugCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favoris': typeof AuthenticatedFavorisRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/codes-promo/$slug': typeof CodesPromoSlugRouteWithChildren
  '/codes-promo/cameroun': typeof CodesPromoCamerounRoute
  '/codes-promo/cote-ivoire': typeof CodesPromoCoteIvoireRoute
  '/codes-promo/senegal': typeof CodesPromoSenegalRoute
  '/live/$id': typeof LiveIdRoute
  '/match/$id': typeof MatchIdRoute
  '/premium/historique': typeof PremiumHistoriqueRoute
  '/premium/tableau-de-bord': typeof PremiumTableauDeBordRoute
  '/codes-promo': typeof CodesPromoIndexRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
  '/api/public/fixture-diagnostic': typeof ApiPublicFixtureDiagnosticRoute
  '/codes-promo/$slug/$country': typeof CodesPromoSlugCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRouteWithChildren
  '/codes-promo': typeof CodesPromoRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/favoris': typeof AuthenticatedFavorisRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/codes-promo/$slug': typeof CodesPromoSlugRouteWithChildren
  '/codes-promo/cameroun': typeof CodesPromoCamerounRoute
  '/codes-promo/cote-ivoire': typeof CodesPromoCoteIvoireRoute
  '/codes-promo/senegal': typeof CodesPromoSenegalRoute
  '/live/$id': typeof LiveIdRoute
  '/match/$id': typeof MatchIdRoute
  '/premium/historique': typeof PremiumHistoriqueRoute
  '/premium/tableau-de-bord': typeof PremiumTableauDeBordRoute
  '/codes-promo/': typeof CodesPromoIndexRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
  '/api/public/fixture-diagnostic': typeof ApiPublicFixtureDiagnosticRoute
  '/codes-promo/$slug/$country': typeof CodesPromoSlugCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/auth'
    | '/codes-promo'
    | '/communaute'
    | '/mentions-legales'
    | '/premium'
    | '/sitemap.xml'
    | '/favoris'
    | '/profil'
    | '/auth/callback'
    | '/codes-promo/$slug'
    | '/codes-promo/cameroun'
    | '/codes-promo/cote-ivoire'
    | '/codes-promo/senegal'
    | '/live/$id'
    | '/match/$id'
    | '/premium/historique'
    | '/premium/tableau-de-bord'
    | '/codes-promo/'
    | '/api/public/fapshi-webhook'
    | '/api/public/fixture-diagnostic'
    | '/codes-promo/$slug/$country'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/auth'
    | '/communaute'
    | '/mentions-legales'
    | '/premium'
    | '/sitemap.xml'
    | '/favoris'
    | '/profil'
    | '/auth/callback'
    | '/codes-promo/$slug'
    | '/codes-promo/cameroun'
    | '/codes-promo/cote-ivoire'
    | '/codes-promo/senegal'
    | '/live/$id'
    | '/match/$id'
    | '/premium/historique'
    | '/premium/tableau-de-bord'
    | '/codes-promo'
    | '/api/public/fapshi-webhook'
    | '/api/public/fixture-diagnostic'
    | '/codes-promo/$slug/$country'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analyse'
    | '/auth'
    | '/codes-promo'
    | '/communaute'
    | '/mentions-legales'
    | '/premium'
    | '/sitemap.xml'
    | '/_authenticated/favoris'
    | '/_authenticated/profil'
    | '/auth/callback'
    | '/codes-promo/$slug'
    | '/codes-promo/cameroun'
    | '/codes-promo/cote-ivoire'
    | '/codes-promo/senegal'
    | '/live/$id'
    | '/match/$id'
    | '/premium/historique'
    | '/premium/tableau-de-bord'
    | '/codes-promo/'
    | '/api/public/fapshi-webhook'
    | '/api/public/fixture-diagnostic'
    | '/codes-promo/$slug/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalyseRoute: typeof AnalyseRoute
  AuthRoute: typeof AuthRouteWithChildren
  CodesPromoRoute: typeof CodesPromoRouteWithChildren
  CommunauteRoute: typeof CommunauteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PremiumRoute: typeof PremiumRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LiveIdRoute: typeof LiveIdRoute
  MatchIdRoute: typeof MatchIdRoute
  ApiPublicFapshiWebhookRoute: typeof ApiPublicFapshiWebhookRoute
  ApiPublicFixtureDiagnosticRoute: typeof ApiPublicFixtureDiagnosticRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes-promo': {
      id: '/codes-promo'
      path: '/codes-promo'
      fullPath: '/codes-promo'
      preLoaderRoute: typeof CodesPromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favoris': {
      id: '/_authenticated/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof AuthenticatedFavorisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/codes-promo/': {
      id: '/codes-promo/'
      path: '/'
      fullPath: '/codes-promo/'
      preLoaderRoute: typeof CodesPromoIndexRouteImport
      parentRoute: typeof CodesPromoRoute
    }
    '/codes-promo/$slug': {
      id: '/codes-promo/$slug'
      path: '/$slug'
      fullPath: '/codes-promo/$slug'
      preLoaderRoute: typeof CodesPromoSlugRouteImport
      parentRoute: typeof CodesPromoRoute
    }
    '/codes-promo/cameroun': {
      id: '/codes-promo/cameroun'
      path: '/cameroun'
      fullPath: '/codes-promo/cameroun'
      preLoaderRoute: typeof CodesPromoCamerounRouteImport
      parentRoute: typeof CodesPromoRoute
    }
    '/codes-promo/cote-ivoire': {
      id: '/codes-promo/cote-ivoire'
      path: '/cote-ivoire'
      fullPath: '/codes-promo/cote-ivoire'
      preLoaderRoute: typeof CodesPromoCoteIvoireRouteImport
      parentRoute: typeof CodesPromoRoute
    }
    '/codes-promo/senegal': {
      id: '/codes-promo/senegal'
      path: '/senegal'
      fullPath: '/codes-promo/senegal'
      preLoaderRoute: typeof CodesPromoSenegalRouteImport
      parentRoute: typeof CodesPromoRoute
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/historique': {
      id: '/premium/historique'
      path: '/historique'
      fullPath: '/premium/historique'
      preLoaderRoute: typeof PremiumHistoriqueRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/premium/tableau-de-bord': {
      id: '/premium/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/premium/tableau-de-bord'
      preLoaderRoute: typeof PremiumTableauDeBordRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/api/public/fapshi-webhook': {
      id: '/api/public/fapshi-webhook'
      path: '/api/public/fapshi-webhook'
      fullPath: '/api/public/fapshi-webhook'
      preLoaderRoute: typeof ApiPublicFapshiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fixture-diagnostic': {
      id: '/api/public/fixture-diagnostic'
      path: '/api/public/fixture-diagnostic'
      fullPath: '/api/public/fixture-diagnostic'
      preLoaderRoute: typeof ApiPublicFixtureDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes-promo/$slug/$country': {
      id: '/codes-promo/$slug/$country'
      path: '/$country'
      fullPath: '/codes-promo/$slug/$country'
      preLoaderRoute: typeof CodesPromoSlugCountryRouteImport
      parentRoute: typeof CodesPromoSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFavorisRoute: typeof AuthenticatedFavorisRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFavorisRoute: AuthenticatedFavorisRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CodesPromoSlugRouteChildren {
  CodesPromoSlugCountryRoute: typeof CodesPromoSlugCountryRoute
}

const CodesPromoSlugRouteChildren: CodesPromoSlugRouteChildren = {
  CodesPromoSlugCountryRoute: CodesPromoSlugCountryRoute,
}

const CodesPromoSlugRouteWithChildren = CodesPromoSlugRoute._addFileChildren(
  CodesPromoSlugRouteChildren,
)

interface CodesPromoRouteChildren {
  CodesPromoSlugRoute: typeof CodesPromoSlugRouteWithChildren
  CodesPromoCamerounRoute: typeof CodesPromoCamerounRoute
  CodesPromoCoteIvoireRoute: typeof CodesPromoCoteIvoireRoute
  CodesPromoSenegalRoute: typeof CodesPromoSenegalRoute
  CodesPromoIndexRoute: typeof CodesPromoIndexRoute
}

const CodesPromoRouteChildren: CodesPromoRouteChildren = {
  CodesPromoSlugRoute: CodesPromoSlugRouteWithChildren,
  CodesPromoCamerounRoute: CodesPromoCamerounRoute,
  CodesPromoCoteIvoireRoute: CodesPromoCoteIvoireRoute,
  CodesPromoSenegalRoute: CodesPromoSenegalRoute,
  CodesPromoIndexRoute: CodesPromoIndexRoute,
}

const CodesPromoRouteWithChildren = CodesPromoRoute._addFileChildren(
  CodesPromoRouteChildren,
)

interface PremiumRouteChildren {
  PremiumHistoriqueRoute: typeof PremiumHistoriqueRoute
  PremiumTableauDeBordRoute: typeof PremiumTableauDeBordRoute
}

const PremiumRouteChildren: PremiumRouteChildren = {
  PremiumHistoriqueRoute: PremiumHistoriqueRoute,
  PremiumTableauDeBordRoute: PremiumTableauDeBordRoute,
}

const PremiumRouteWithChildren =
  PremiumRoute._addFileChildren(PremiumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalyseRoute: AnalyseRoute,
  AuthRoute: AuthRouteWithChildren,
  CodesPromoRoute: CodesPromoRouteWithChildren,
  CommunauteRoute: CommunauteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PremiumRoute: PremiumRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LiveIdRoute: LiveIdRoute,
  MatchIdRoute: MatchIdRoute,
  ApiPublicFapshiWebhookRoute: ApiPublicFapshiWebhookRoute,
  ApiPublicFixtureDiagnosticRoute: ApiPublicFixtureDiagnosticRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
