/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedFavorisRouteImport } from './routes/_authenticated/favoris'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as ApiPublicFapshiWebhookRouteImport } from './routes/api/public/fapshi-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavorisRoute = AuthenticatedFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFapshiWebhookRoute = ApiPublicFapshiWebhookRouteImport.update({
  id: '/api/public/fapshi-webhook',
  path: '/api/public/fapshi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favoris': typeof AuthenticatedFavorisRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/live/$id': typeof LiveIdRoute
  '/match/$id': typeof MatchIdRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favoris': typeof AuthenticatedFavorisRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/live/$id': typeof LiveIdRoute
  '/match/$id': typeof MatchIdRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/favoris': typeof AuthenticatedFavorisRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/live/$id': typeof LiveIdRoute
  '/match/$id': typeof MatchIdRoute
  '/api/public/fapshi-webhook': typeof ApiPublicFapshiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/auth'
    | '/communaute'
    | '/mentions-legales'
    | '/premium'
    | '/sitemap.xml'
    | '/favoris'
    | '/profil'
    | '/auth/callback'
    | '/live/$id'
    | '/match/$id'
    | '/api/public/fapshi-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/auth'
    | '/communaute'
    | '/mentions-legales'
    | '/premium'
    | '/sitemap.xml'
    | '/favoris'
    | '/profil'
    | '/auth/callback'
    | '/live/$id'
    | '/match/$id'
    | '/api/public/fapshi-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analyse'
    | '/auth'
    | '/communaute'
    | '/mentions-legales'
    | '/premium'
    | '/sitemap.xml'
    | '/_authenticated/favoris'
    | '/_authenticated/profil'
    | '/auth/callback'
    | '/live/$id'
    | '/match/$id'
    | '/api/public/fapshi-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalyseRoute: typeof AnalyseRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunauteRoute: typeof CommunauteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PremiumRoute: typeof PremiumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LiveIdRoute: typeof LiveIdRoute
  MatchIdRoute: typeof MatchIdRoute
  ApiPublicFapshiWebhookRoute: typeof ApiPublicFapshiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favoris': {
      id: '/_authenticated/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof AuthenticatedFavorisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fapshi-webhook': {
      id: '/api/public/fapshi-webhook'
      path: '/api/public/fapshi-webhook'
      fullPath: '/api/public/fapshi-webhook'
      preLoaderRoute: typeof ApiPublicFapshiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFavorisRoute: typeof AuthenticatedFavorisRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFavorisRoute: AuthenticatedFavorisRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalyseRoute: AnalyseRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunauteRoute: CommunauteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PremiumRoute: PremiumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LiveIdRoute: LiveIdRoute,
  MatchIdRoute: MatchIdRoute,
  ApiPublicFapshiWebhookRoute: ApiPublicFapshiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
