-- First-party conversion events. No email, secret, raw user agent or ad identifier is stored.
CREATE TABLE IF NOT EXISTS public.conversion_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  session_id TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  route TEXT,
  source TEXT,
  medium TEXT,
  campaign TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.conversion_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.conversion_events FROM anon, authenticated;
GRANT ALL ON public.conversion_events TO service_role;

CREATE INDEX IF NOT EXISTS idx_conversion_events_created
  ON public.conversion_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversion_events_event_created
  ON public.conversion_events(event_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversion_events_session_created
  ON public.conversion_events(session_id, created_at DESC);
